warns = [
    "absolute_paths",
    "alloc_instead_of_core",
    "allow_attributes",
    "allow_attributes_without_reason",
    "arithmetic_side_effects",
    "as_conversions",
    "assertions_on_constants",
    "cargo",
    "cast_possible_truncation",
    "cast_possible_wrap",
    "cast_precision_loss",
    "cast_sign_loss",
    "checked_conversions",
    "clippy::all",
    "clippy::complexity",
    "clippy::correctness",
    "clippy::nursery",
    "clippy::pedantic",
    "clippy::perf",
    "clippy::restriction",
    "clippy::style",
    "dbg_macro",
    "decimal_literal_representation",
    "default_numeric_fallback",
    "empty_drop",
    "empty_enum",
    "empty_structs_with_brackets",
    "explicit_deref_methods",
    "explicit_into_iter_loop",
    "filetype_is_file",
    "float_cmp",
    "fn_params_excessive_bools",
    "future_not_send",
    "imprecise_flops",
    "inconsistent_struct_constructor",
    "indexing_slicing",
    "inefficient_to_string",
    "let_underscore_must_use",
    "let_underscore_untyped",
    "lossy_float_literal",
    "macro_use_imports",
    "manual_assert",
    "manual_ok_or",
    "map_err_ignore",
    "missing_docs",
    "missing_enforced_import_renames",
    "missing_inline_in_public_items",
    "missing_safety_doc",
    "missing_trait_methods",
    "module_name_repetitions",
    "mut_mut",
    "needless_collect",
    "panic",
    "panicking_unwrap",
    "pub const_enum",
    "pub_use",
    "question_mark_used",
    "redundant_closure",
    "shadow_unrelated",
    "single_match_else",
    "string_slice",
    "todo",
    "trivially_copy_pass_by_ref",
    "undocumented_unsafe_blocks",
    "unimplemented",
    "unnecessary_safety_comment",
    "unnecessary_self_imports",
    "unneeded_field_pattern",
    "unnested_or_patterns",
    "unreachable",
    "unsafe_code",
    "unused_self",
    "unused_unit",
    "use_self",
    "wildcard_dependencies",
    "wildcard_imports"
]

allow = [
    "missing_copy_implementations",
    "missing_debug_implementations",
    "similar_names"
]

